## 2.3 线性代数
### 2.3.1 标量
标量由只有一个元素的张量表示。

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

### 2.3.2 向量
你可以将向量视为标量值组成的列表。我们将这些标量值称为向量的元素(element)或分量(component)。当向量表示数据集中的样本时，它们的值具有一定的现实意义。

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
#使用张量的索引访问任意元素
x[3]

tensor(3)

**长度、维度和形状**

向量只是一个数字数组，就像每个数组都有一个长度一样，每个向量也是如此。在数学表示法中，如果我们想说一个向量$x$由n个实值标量组成，我们都可以将其表示为$x \in \mathbb R^n$。向量的长度通常称为向量的维度(dimension)

In [4]:
#与普通的Python数组一样，我们可以通过Python内置的len()函数来访问张量的长度。
len(x)

4

In [5]:
#也可以使用.shape属性访问向量的长度
x.shape

torch.Size([4])

### 2.3.3 矩阵
正如向量将标量从零阶推广到一阶，矩阵将向量丛一阶推广到二阶。矩阵，我们通常用粗体、大写字母来表示，在代码中表示为具有两个轴的张量。

在数学表示法中，我们使用$A \in \mathbb R^{m \times n}$来表示矩阵**A**，其由m行和n列的实值标量组成。我们可以将任意矩阵$A \in \mathbb R^{m \times n}$视为一个表格，其中元素$a_{ij}$属于第i行第j列：

$$
\begin{bmatrix} a_{11} & a_{12} & ··· & a_{1n} \\ a_{21} & a_{22} & ··· & a_{2n} \\ · & · &  & ·· \\
· & · &  & ·· \\ a_{m1} & a_{m2} & ·· & a_{mn}
\end{bmatrix}
\quad
$$

对于任意的$A \in \mathbb R^{m \times n}$，**A**的形状是$(m,n)$或$m \times n$。当矩阵具有相同数量的行和列时，其形状将变为正方形；因此，它被称为方针(square matrix)。

当调用函数来实例化张量时，我们可以通过指定两个分量m和n来创建一个形状为$m \times n$的矩阵。

In [6]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

我们可以通过行索引$(i)$和列索引$(j)$来访问矩阵中的标量元素$a_{ij}$，例如$[A]_{ij}$。

当我们交换矩阵的行和列时，结果称为矩阵的转置(transpose)。我们用$a^T$来表示矩阵的转置，如果$B=A^T$，则对于任意$i和j$，都有$b_{ij}=a_{ji}。因此，在(2.3.2)中的矩阵转置是一个形状为$n \times m$的矩阵：

$$
\begin{bmatrix} a_{11} & a_{21} & ··· & a_{m1} \\ a_{12} & a_{22} & ··· & a_{m2} \\ · & · &  & ·· \\
· & · &  & ·· \\ a_{1n} & a_{2n} & ·· & a_{mn}
\end{bmatrix}
\quad
$$


In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

作为方阵的一种特殊类型，对称矩阵(symmetric matrix)$A$等于其转置:$A = A^T$。

In [8]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [9]:
#现在我们将B和它的转置进行比较
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

矩阵是有用的数据结构：它们允许我们组织具有不同模式的数据。

### 2.3.4 张量
张量为我们提供了描述具有任意数量轴的$n$维数组的通用方法。张量用特殊字体的大写字母表示，它们的索引机制与矩阵类似。

当我们开始处理图像时，张量将变得更加重要，图像以$n$维数组形式出现，其中3个轴对应于高度、宽度以及一个通道(channel)轴，用于表示颜色通道(红色、绿色和蓝色)。

In [11]:
X = torch.arange(24).reshape(2, 3, 4)

X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 2.3.5 张量算法的基本性质
标量、向量、矩阵和任意数量轴的张量有一些实用的属性。例如，你可能已经从按元素操作的定义中注意到，任何元素的一元运算都不会改变其操作数的形状。同样，给定具有相同形状的任意两个张量，任何按元素二元运算的结果都是相同形状的张量。例如，将两个相同形状的矩阵相加，会在这两个矩阵上执行元素加法。

In [12]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

具体而言，两个矩阵的按元素乘法称为Hadamard积。